# These are supported funding model platforms

github: [sawyeriii, doctoratat, primalmath, dratat] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: sawyeriii # Replace with a single Patreon username
open_collective: sawyeriii # Replace with a single Open Collective username
ko_fi: sawyeriii # Replace with a single Ko-fi username
tidelift: sawyeriii/BLISBoot # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: DSMComm-ipfs # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: sawyeriii # Replace with a single Liberapay username
issuehunt: sawyeriii # Replace with a single IssueHunt username
otechie: sawyeriii # Replace with a single Otechie username
custom: ['ipfs.dsmcommunications.com','iEllenTARDiS.ipfs','iEllenTARDiS.dsmcommunications.com','ipfs://iEllenTARDiS.attlocal.net'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
